baseURL: https://rphilips.github.io/qtechng-blog/
publishDir: docs
languageCode: nl-nl
title: QtechNG Blog
theme: ananke
DefaultContentLanguage: nl
SectionPagesMenu: main
Paginate: 9
background_color_class: bg-black
recent_posts_number: 4
markup:
  highlight:
      codeFences: true
      guessSyntax: false
      hl_Lines: ""
      lineNoStart: 1
      lineNos: false
      lineNumbersInTable: true
      noClasses: true
      style: solarized-light
      tabWidth: 4


